import Head from 'next/head'
import { BsFillMoonStarsFill,BsSunFill } from 'react-icons/bs'
import { 
  AiFillTwitterCircle, 
  AiFillLinkedin, 
  AiFillYoutube, 
  AiFillGithub
} from 'react-icons/ai'  
import Image from 'next/image'
import deved from '../public/caricatura.jpeg'
import brazil from '../public/brazil.png'
import prover from '../public/prover.png'
import america from '../public/united-states.png'
import bellfix from '../public/bellfix.png'
import ericsson from '../public/ericsson.png'
import fortiori from '../public/fort.png'
import roit from '../public/roit.png'
import vegait from '../public/vega.png'
import nexuz from '../public/nexuz.png'
import gocoffee from '../public/gocoffee.jpg'
import innovsoftware from '../public/innov.png'
import { useState } from 'react'
import Link from 'next/link'
import{useRouter} from 'next/router'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import DataTable from './components/table/table'
import SimpleAccordion from './components/accordion/accordion'

 const Home = () => {
  const [darkMode, setDarkMode] = useState(false);
  const { locale, locales, push } = useRouter()
  const { t:translate } = useTranslation('home')

  console.log(locale)
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Henrique Tiago Tyminski Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section>
          <nav className='py-10 mb-12 flex justify-between'>
            <div width={200}>
              <Link href={`/`} locale='en' className='mr-4' >
                <Image className='inline-block' src={america} width={30} height={15} />
              </Link>
              <Link href={`/`} locale='pt' className='ml-4'>
                <Image className='inline-block' src={brazil} width={30} height={15} />
              </Link>
            </div>
            <div width={200}>
              {darkMode 
                ? 
                <BsSunFill className="cursor-pointer text-2xl dark:text-white"
                  onClick={() => setDarkMode(!darkMode)}
                />
                :
                <BsFillMoonStarsFill 
                  className="cursor-pointer text-2xl dark:text-white"
                  onClick={() => setDarkMode(!darkMode)}
                />
              }
            </div>
          </nav>
          <div className='text-center p-10'>
            <a 
                href="https://drive.google.com/file/d/1InmU-I3j-rQZVOZHCevi2K8hwnMTMNLB/view?usp=share_link"
                target="_blank"
                className='bg-gradient-to-r from-cyan-700 to-teal-600 text-white px-4 py-2 borer-none rounded-lg ml-8'
              >
                CV EN
              </a>
              <a 
                href="https://drive.google.com/file/d/1Q-147z-Ev_8GqLZHS2NGW80L5GuAC0xw/view?usp=share_link"
                target="_blank"
                className='bg-gradient-to-r from-cyan-700 to-teal-600 text-white px-4 py-2 borer-none rounded-lg ml-8'
              >
                CV BR
              </a>
          </div>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Henrique Tiago Tyminski</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-gray-400'>Software Engineer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-400'>
            {translate('subTitleHome')}
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3'>
            <a href="https://twitter.com/home" target="_blank">
              <AiFillTwitterCircle className='text-gray-600 hover:text-sky-600' />
            </a>
            <a href="https://www.linkedin.com/in/henrique-tiago-tyminski-1b2719158/" target="_blank">
              <AiFillLinkedin className='text-gray-600 hover:text-sky-800' />
            </a>
            <a href="https://www.youtube.com/channel/UClTxDoKADP0OwXEzUUgCAEg" target="_blank">
              <AiFillYoutube className='text-gray-600 hover:text-red-600' />
            </a>
            <a href="https://github.com/HTTyminski" target="_blank">
              <AiFillGithub className='text-gray-600 hover:text-stone-800' />
            </a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-86 md:w-86'>
            <Image src={deved} layout="fill"  alt='imagem'/>
          </div>
        </section>
        <section>
          <div className='py-10'>
            <h3 className='text-3xl py-1 dark:text-gray-600'>{translate('servicesIOffer')}</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
              {translate('passionate')}
            </p>
            <p className='text-md leading-4 text-gray-800 dark:text-gray-400'>
              {translate('offer')}
            </p>
          </div>
        </section >
        <section className='my-10 dark:text-gray-600'>
          <SimpleAccordion />
        </section>
        <section className='my-10 dark:text-gray-600'>
          <div className='py-10'>
            <h3 className='text-3xl py-1 dark:text-gray-600'>Github </h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
              {translate('studyProjects')}
            </p>
          </div>
          <DataTable />
        </section>
        <section className='pb-10'>
          <div className='py-10'>
            <h3 className='text-3xl py-1 dark:text-gray-600'>{translate('companies')}</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
              {translate('projects')}
            </p>
          </div>
          <div className='flex mb-5'>
            <Image 
              src={bellfix} 
              className="rounded-lg object-cover "
              width={50}
              height={50}
            />
            <Image 
              src={ericsson} 
              className="rounded-lg object-cover ml-5 " 
              width={50}
              height={50}
            />
            <Image 
              src={nexuz} 
              className="rounded-lg object-cover ml-5"
              width={50}
              height={50}
            />
            <Image 
              src={roit} 
              className="rounded-lg object-cover ml-5" 
              width={50}
              height={50}
            />
            <Image 
              src={vegait} 
              className="rounded-lg object-cover ml-5" 
              width={50}
              height={50}
            />
            </div>
             <div className='flex '>
            <Image 
              src={gocoffee} 
              className="rounded-lg object-cover" 
              width={50}
              height={50}
            />
            <Image 
              src={innovsoftware} 
              className="rounded-lg object-cover ml-5" 
              width={50}
              height={50}
            />
            <Image 
              src={fortiori} 
              className="rounded-lg object-cover ml-5" 
              width={50}
              height={50}
            />
            <Image 
              src={prover} 
              className="rounded-lg object-cover ml-5" 
              width={50}
              height={50}
            />
          </div>
        </section>
      </main>
    </div>
  )
}

export async function getStaticProps({ locale }){
  return {
    props: {
        ...(await serverSideTranslations(locale, ['home'])),
    }
  }
}

export default Home
